default_connection_name = "sync_streamlit"

[connections]
[connections.sync_streamlit]
user = "ISHAN"
password = "9v5q_]jM*VS}W3D"
account = "qg94313.ap-south-1"
warehouse = "LL_STG_WH"
database = "LL_PROD_RAW_ZONE"
schema = "PUBLIC"